### ISSUE TITLE
performance is bad on crystal 0.13

### ISSUE THREAD

**Issue by chenkovsky** [crystal-lang/sublime-crystal#14]
after I upgrade crystal to 0.13, sublime runs slowly. I can't even edit crystal files.
but atom editor works fine.

**Comment by asterite** [comment]
Hi,

It works fine for me. What do you mean it's slow? Is it only slow for editing crystal files? Or any file? Maybe you have some other plugin that slows down things?

**Comment by chenkovsky** [comment]
it is only slow for editing crystal files. but it also works fine now. I don't known why. are there something like retagging or indexing that are running in the background?

**Comment by asterite** [comment]
Sometimes sublime reindexes stuff in the background, but it has nothing to do with Crystal's plugin. I also experience slowdows when there are lots of files in the current project (and they are not ignored by sublime).

Crystal's plugin just does syntax highlighting (that shouldn't be slow, it's mostly a copy of ruby's syntax highlighting with a few tweaks) and formats your code when you save a file, but that should be (super) fast too.

**Comment by chenkovsky** [comment]
thank you, it seems that it's caused by sublime, nothing to do with your plugin.😊
