### ISSUE TITLE
Removes lines on save

### ISSUE THREAD

**Issue by schoening** [crystal-lang/sublime-crystal#17]
I don't know if I am the only one experiencing this, but when I press save the plugin removes all the empty lines in my program..
The indentation is useful. But I want some whitespace between some of my code blocks.
Does anyone have a solution for this?

**Comment by bcardiff** [comment]
It is the [behavior of the formatter](https://github.com/crystal-lang/crystal/blob/master/spec/compiler/formatter/formatter_spec.cr#L540) and it is not customizable. It helps to have a unified format.

**Comment by schoening** [comment]
Ah.. okey. Sometimes I am able to have a single empty line, most times I cannot. Can you tell me why that happens?

**Comment by schoening** [comment]
I asked around on gitter and it seems that I am the only one who was having this problem.
My issue was that absolutely no empty lines where allowed. Not even 1.
So I did a clean install of sublime and now the plugin works.
Seems I had some issue with other conflicting packages. Closing this now :)
